### PR TITLE
Bump golangci-lint to v1.40.1

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták gliptak@gmail.com

### CODE REVIEW

**Comment by gliptak** [comment]
```
internal/mod/mod.go:9:13: fieldalignment: struct with 136 pointer bytes could be 120 (govet)
```

**Comment by psampaz** [comment]
Hi @gliptak, thanks for you PR. 

Please add fieldalignment to the list of disable linters here https://github.com/psampaz/go-mod-outdated/blob/master/.golangci.yml#L46

I really do not see any value on spending time optimizing this. The gain is insignificant.

**Comment by Deseao** [comment]
I believe if you run `go run golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment -fix ./internal/mod` it will automatically align the struct for you.

**Comment by psampaz** [comment]
@gliptak after @Deseao comment i realized that this a go vet analyzer and no an independent one. This needs to be excluded in the settings of go vet inside the golangci.yml

**Pull request closed without merging**
